# Nome da Aplicacao
spring.application.name=arena-match
server.port=8080

# Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/arena_match_dev
spring.datasource.username=arena
spring.datasource.password=arena987
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false

# Flyway (Migracao)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# PrimeFaces
joinfaces.primefaces.theme=saga
primefaces.csp=true
primefaces.font-awesome=true